!com.braintribe.devrock.model.repository.RepositoryConfiguration {
  cachePath: "${config.base}/../repo",

  repositories: [
    !com.braintribe.devrock.model.repository.MavenHttpRepository {
      name: "core-dev", 
      url: "https://maven.pkg.github.com/hiconic-os/maven-repo-dev", 
      user: "${env.OPENTF_REPO_USER}",
      password: "${env.OPENTF_REPO_PASSWORD}",
      dominanceFilter: !com.braintribe.devrock.model.repository.filters.AllMatchingArtifactFilter {},
    },
    !com.braintribe.devrock.model.repository.MavenHttpRepository {
      name: "third-party", 
      url: "https://repo1.maven.org/maven2/", 
    },
  ]
}