!com.braintribe.devrock.model.repository.RepositoryConfiguration {
  cachePath: "${config.base}/../repo",

  repositories: [
    !com.braintribe.devrock.model.repository.MavenHttpRepository {
      name: "hiconic-dev",
      url: "https://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@maven.pkg.github.com/hiconic-os/maven-repo-dev",
      dominanceFilter: !com.braintribe.devrock.model.repository.filters.AllMatchingArtifactFilter {},
    },
    !com.braintribe.devrock.model.repository.MavenHttpRepository {
      name: "third-party", 
      url: "https://repo1.maven.org/maven2/", 
    },
  ]
}