!com.braintribe.devrock.model.repository.RepositoryConfiguration {
  cachePath: "${config.base}/../repo",

  repositories: [
    !com.braintribe.devrock.model.repository.IndexedMavenHttpRepository {
      name: "hiconic-os-dev",
      url: "https://${env.GITHUB_READ_PACKAGES_TOKEN}@maven.pkg.github.com/hiconic-os/maven-repo-dev",
      dominanceFilter: !com.braintribe.devrock.model.repository.filters.AllMatchingArtifactFilter {},
    },
    !com.braintribe.devrock.model.repository.MavenHttpRepository {
      name: "third-party", 
      url: "https://repo1.maven.org/maven2/", 
    },
  ]
}